//STOCK DE 46 SOLES

const detalleStock = [
    {
        id: 1,
        objeto: "Maceta",
        nombre: "Face",
        descripcion: "Macetas con rostros pintados a mano",
        color: "blanco y negro",
        stock: "10",
        precio: "$ 1000",
    },
    {
        id: 2,
        objeto: "Maceta",
        nombre: "Lady",
        descripcion: "Macetas hecha con forma de cuerpo",
        color: "blanco y negro",
        stock: "12",
        precio: "$ 1500",
    },
    {
        id: 3,
        objeto: "Maceta",
        nombre: "Black&White",
        descripcion: "Macetas con diseños abstractos",
        color: "blanco y negro",
        stock: "8",
        precio: "$ 2000",
    },
    {
        id: 4,
        objeto: "Colgante",
        nombre: "Arcoiris",
        descripcion: "Adorno de alambre en forma de Arcoiris decorado con piedras transparentes",
        color: "Alambre peltre piedras de colores",
        stock: "15",
        precio: "$ 1100",
    },
    {
        id: 5,
        objeto: "Colgante",
        nombre: "Arbol",
        descripcion: "Adorno de alambre en forma de Arbol decorado con piedras transparentes",
        color: "Alambre peltre piedras de colores",
        stock: "18",
        precio: "$ 1200",
    },
    {
        id: 6,
        objeto: "Colgante",
        nombre: "Mariposa",
        descripcion: "Adorno de alambre en forma de Mariposa decorado con piedras transparentes",
        color: "Alambre peltre piedras de colores",
        stock: "14",
        precio: "$ 1300",
    },
    {
        id: 7,
        objeto: "Cuadro",
        nombre: "Triptico Arbol",
        descripcion: "Cuadro Triptico con figura Arbol en un Atardecer",
        color: "varios colores",
        stock: "5",
        precio: "$ 5000",
    },
    {
        id: 8,
        objeto: "Cuadro",
        nombre: "Abstracto",
        descripcion: "Cuadro Abstracto de varios colores",
        color: "varios colores",
        stock: "10",
        precio: "$ 6000",
    },
];